apiVersion: config.istio.io/v1alpha2
kind: QuotaSpec
metadata:
  name: request-quota
spec:
  rules:
    - quotas:
        - quota: request-count
          max: 1000
          validDuration: 1m
---
apiVersion: config.istio.io/v1alpha2
kind: QuotaSpecBinding
metadata:
  name: request-quota-binding
spec:
  quotaSpecs:
    - name: request-quota
  services:
    - name: backend-service
      namespace: default
