apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-analytics-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-analytics-service
  template:
    metadata:
      labels:
        app: go-analytics-service
    spec:
      containers:
        - name: go-analytics-service
          image: xnl-microservices-go
          ports:
            - containerPort: 9000
