version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: xnl_db
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  cassandra:
    image: cassandra:latest
    ports:
      - "9042:9042"

  clickhouse:
    image: clickhouse/clickhouse-server
    ports:
      - "8123:8123"
